SELECT DISTINCT A.COD_BODEGA 
FROM OPENQUERY(RSCLPAN,'
    SELECT COD_BODEGA 
    FROM AL_MOVIMIENTOS
    WHERE NOM_USUARORA = ''MIGRAPP''
    AND TIP_STOCK IN (''2'', ''10'')
    AND COD_ARTICULO IN (
        ''1894''
    )
    
') AS A
LEFT JOIN migracion_mapeo_06102023 AS B ON A.COD_BODEGA = B.COD_BODEGA_SCL
WHERE B.COD_BODEGA_SCL IS NULL;
